services:
  match-adapter:
    build:
      context: .
      dockerfile: cmd/match-adapter/Dockerfile
    image: fan-avia/match-adapter:local
    container_name: match-adapter
    ports:
      - "8086:8086"
      - "44045:44045"
    env_file:
      - ./cmd/match-adapter/.env
    environment:
      DEBUG_HTTP_ENABLED: "true"
      DEBUG_HTTP_HOST: "0.0.0.0"
      GRPC_HOST: "0.0.0.0"
      GRPC_PORT: "44045"
      DEBUG_HTTP_PORT: "8086"
      REDIS_ADDR: redis:6379
      JAEGER: jaeger:14268

  airfare-provider:
    build:
      context: .
      dockerfile: cmd/airfare-provider/Dockerfile
    image: fan-avia/airfare-provider:local
    container_name: airfare-provider
    ports:
      - "44044:44044"
    env_file:
      - ./cmd/airfare-provider/.env
    environment:
      GRPC_HOST: "0.0.0.0"
      GRPC_PORT: "44044"
      REDIS_ADDR: redis:6379
      MATCH_ADAPTER_HOST: match-adapter
      MATCH_ADAPTER_PORT: "44045"
      JAEGER: jaeger:14268
    depends_on:
      - match-adapter

  api-gateway:
    build:
      context: .
      dockerfile: cmd/api-gateway/Dockerfile
    image: fan-avia/api-gateway:local
    container_name: api-gateway
    ports:
      - "8100:8100"
    environment:
      AIRFARE_ADDRESS: airfare-provider:44044
      MATCH_ADDRESS: match-adapter:44045
      JAEGER_ADDRESS: jaeger:14268
      HTTP_PORT: "8100"
    depends_on:
      - airfare-provider
      - match-adapter


  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      BASE_URL: /docs
      NGINX_ROOT: /usr/share/nginx/html
      SWAGGER_JSON: /docs/openapi.yaml
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro
    depends_on:
      - api-gateway


