version: "3"
tasks:
  up:
    deps: [run-api, run-airfare, run-match]

  run-api:
    dir: ./cmd/api-gateway
    cmds:
      - go run ./cmd/main.go --config=./config/local.yaml

  run-airfare:
    dir: ./cmd/airfare-provider
    cmds:
      - go run ./cmd/main.go --config=./config/local.yaml

  run-match:
    dir: ./cmd/match-adapter
    cmds:
      - go run ./cmd/main.go --config=./config/local.yaml
